apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-app-deployment
  labels:
    name: redis-app-deployment
    app: demo-voting-app
spec:
  replicas: 2
  selector:
    matchLabels:
      name: redis-app-pod
      app: demo-voting-app
  template:
    metadata:
      name: redis-pod
      labels:
        name: redis-pod
        app: demo-voting-app
    spec:
      containers:
        - name: redis-pod-container
          image: redis
          ports:
            - containerPort: 6379